// AUTO-GENERATED by scripts/build-contact-art.mjs. Do not edit by hand.
// To update: drop a logo into static/logos/<slug>.{svg,png} and run `node scripts/build-contact-art.mjs`.

export const contactArt: Record<string, string> = {
  "email": "\n\n +=*%@@@@@@@@%*=+\n @%*=+#@@@@%+=*%@\n @@@@#==##==#@@@@\n @@@@@@%++%@@@@@@\n @@@@@@@@@@@@@@@@\n\n",
  "github": "     %%%%%%%%\n   %%%%%%%%%%%%\n %%%% %%%%%% %%%%\n %%%          %%%\n%%%%          %%%%\n%%%%%         %%%%\n %%%%%%    %%%%%%\n  %%%%%    %%%%%\n    %%%    %%",
  "linkedin": "++++++++++++++++++\n+++:,-++++++++++++\n+++,,-++++++++++++\n+++::=+::-:,,:=+++\n+++,,:+,,,,:,,,+++\n+++,,:+,,,++:,,+++\n+++,,:+,,,++:,,+++\n+++::-+::-++-::+++\n++++++++++++++++++",
  "instagram": "\n   @@@@@@@@@@@@\n  @@@@@@%%@@=+@@\n  @@@@+:--:+%@@@\n  @@@@,-@@-,@@@@\n  @@@@+:--:+@@@@\n  @@@@@@%%@@@@@@\n   @@@@@@@@@@@@\n"
};
